source 'http://rubygems.org'
source 'http://gemcutter.org'
source 'http://gems.github.com'

gem 'rails', '3.0.0'
gem 'pg'
gem 'devise'
gem 'delayed_job'
gem 'google_analytics'
gem 'jquery-rails'
gem 'will_paginate', '=3.0.pre2'
gem 'carrierwave-rails3'
gem 'httparty'
gem 'hoptoad_notifier'

group :development do
  gem 'annotate'
  gem 'heroku_san'
  gem 'jquery-rails'
end

group :test, :development do
  gem 'webrat'
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails', '>= 2.0.0.beta.22'
  gem 'email_spec'
  gem 'spork'
  gem 'launchy'
end
